/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by apiregister-gen. Do not edit it manually!

package v1beta1

import (
	"github.com/kubernetes-incubator/apiserver-builder/pkg/builders"
	"github.com/tamalsaha/apiserver-builder-demo/pkg/apis/insect"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apiserver/pkg/registry/rest"
)

var (
	insectBeeStorage = builders.NewApiResource( // Resource status endpoint
		insect.InternalBee,
		BeeSchemeFns{},
		func() runtime.Object { return &Bee{} },     // Register versioned resource
		func() runtime.Object { return &BeeList{} }, // Register versioned resource list
		&BeeStrategy{builders.StorageStrategySingleton},
	)
	ApiVersion = builders.NewApiVersion("insect.tamalsaha.com", "v1beta1").WithResources(
		insectBeeStorage,
		builders.NewApiResource( // Resource status endpoint
			insect.InternalBeeStatus,
			BeeSchemeFns{},
			func() runtime.Object { return &Bee{} },     // Register versioned resource
			func() runtime.Object { return &BeeList{} }, // Register versioned resource list
			&BeeStatusStrategy{builders.StatusStorageStrategySingleton},
		), builders.NewApiResourceWithStorage(
			insect.InternalScaleBeeREST,
			builders.SchemeFnsSingleton,
			func() runtime.Object { return &Scale{} }, // Register versioned resource
			nil,
			func() rest.Storage { return &ScaleBeeREST{insect.NewBeeRegistry(insectBeeStorage)} },
		),
	)

	// Required by code generated by go2idl
	AddToScheme        = ApiVersion.SchemaBuilder.AddToScheme
	SchemeBuilder      = ApiVersion.SchemaBuilder
	localSchemeBuilder = &SchemeBuilder
	SchemeGroupVersion = ApiVersion.GroupVersion
)

// Required by code generated by go2idl
// Kind takes an unqualified kind and returns a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Required by code generated by go2idl
// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}

//
// Bee Functions and Structs
//
// +k8s:deepcopy-gen=false
type BeeSchemeFns struct {
	builders.DefaultSchemeFns
}

// +k8s:deepcopy-gen=false
type BeeStrategy struct {
	builders.DefaultStorageStrategy
}

// +k8s:deepcopy-gen=false
type BeeStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type BeeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Bee `json:"items"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type ScaleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Scale `json:"items"`
}
